### ISSUE TITLE
Versioning 

### ISSUE THREAD

**Issue by bobgodwinx** [RxSwiftCommunity/Action#115]
### Currently

The current version of `Action`  reads `s.version = "3.3.0-alpha.1` 

### Required

A clear strategy on how to better do the versioning of `Action` if I may suggest we could follow the `RxSwift` versioning since we are depending on it as our main dependency framework

**Comment by ashfurrow** [comment]
I've had bad experiences tying library version numbers to version numbers of a dependency – I think we should keep them independent. Otherwise, we follow [semantic versioning](http://semver.org) (so, breaking changes to Action would be a major version, but adding support for Swift 4 or RxSwift 4 would be a patch). CocoaPods handles resolving all the version numbers and stuff, I think Carthage is a little more hands-on but can still work. Thoughts?

**Comment by bobgodwinx** [comment]
@ashfurrow You have a valid point here also. Based on this document a `Patch` is a `Z` which means from `s.version = "3.3.0-alpha.1` to `s.version = "3.3.1` The only problem is that some people might get confused.. in relation to the previous version of `RxSwift  3.x.x`. But this could definitely be a valid solution. @fpillet @freak4pc please take a look at [http://semver.org](semantic versioning) let's hear your opinions.

**Comment by ashfurrow** [comment]
Argh, I think I misspoke. It would be a point release, an X. So `s.version = "3.4.0"` because it adds a new feature. That's my interpretation. Regardless of what we pick, we should add something to the readme or here: https://github.com/RxSwiftCommunity/contributors

**Comment by bobgodwinx** [comment]
@ashfurrow Got it. `3.4.0` sounds reasonable. I am in for that. Let's see what others say.

**Comment by freak4pc** [comment]
Sorry, I just saw your ping. I agreed with the 3.4.0 versioning here. Regardless of RxSwift, this is a minor update and not a patch anyways :) Thanks @bobgodwinx !
