### ISSUE TITLE
Kotlin/Android counterpart

### ISSUE THREAD

**Issue by JoaquimLey** [RxSwiftCommunity/Action#140]
Hello, 

Wondering if you guys could help out with a `question`:

- Are aware of any implementation or
- Any reason/blocker why there isn't

a Kotlin/Android version of this awesome _tool_

For reference, we **did ask on SO** but got no _answer_: 
https://stackoverflow.com/questions/49031599/rxswift-like-actions-for-android

**Comment by ashfurrow** [comment]
Hi there 👋 I'm not aware of any ports, but I have nearly zero visibility into the Android ecosystem. If you've looked wherever Android dependencies are collected and can't find one, there probably isn't one yet. Maybe open an issue on https://github.com/ReactiveX/RxKotlin or https://github.com/ReactiveX/RxJava to ask? 

I don't think there's any _technical_ reason why a port wouldn't work but again, I'm not familiar with those languages. This library is itself a port of a class from ReactiveCocoa, which is an Objective-C library. So porting the "Action" abstraction across languages has precedent. I would imagine no one has done it yet simply because no one has thought of it. I'm sure you'd be able to write out a successful port with some time and patience. 

Good luck, if you do manage to find something or write something, please drop us a line to let us and others know. Good luck!

**Comment by JoaquimLey** [comment]
Hey @ashfurrow 👋,

Thanks for your feedback and tips, I guess the solution is to write it out, I will write back if I get any update(s) 

Thanks 💪

**Comment by JoaquimLey** [comment]
Hello again @ashfurrow 👋 

Just published `v0.0.1` 🎉. Decided to call it **KAction** since is written in Kotlin ❤️.
Check it out when you have a moment:
- https://github.com/tonsser/kaction

**Comment by ashfurrow** [comment]
That's so cool, congratulations! One note: in the readme, you say `SwiftCommunity` instead of `RxSwiftCommunity`. But yeah, excellent work! 

Are you comfortable closing this issue?

**Comment by JoaquimLey** [comment]
Terribly sorry or that!
I've fixed it: https://github.com/tonsser/kaction/commit/91b001250a5a55aec4f071ef96381970d7d45f68

Once again thank your time and this awesome tool, we rely on it [@tonsser](https://github.com/tonsser/)!

💪
