### ISSUE TITLE
UIRefreshControl support

### ISSUE THREAD

**Issue by Denages** [RxSwiftCommunity/Action#141]
As this project grows from RACCommand I'm expecting it to support UIRefreshControl. Are there any plans to handle it?

**Comment by ashfurrow** [comment]
Hi! We don't have plans to _not_ handle, it's just never been something we've needed. If you are free, I'd love to review a pull request that adds support for it!

**Comment by bobgodwinx** [comment]
@Denages can't really get what you asking for can you elaborate further? Because `UIRefreshControl` is already covered in `RxCocoa`

**Comment by stefanomondino** [comment]
I think he's referring to something like 
` refreshControl.rx.bind(to:action, input:someInput) ` or similar binding methods.
In this way, the refresh control can trigger some reload action and be notified (and animated) when executing status changes. It's been a while since last time I've used a RACCommand, but i think it used to work like this.
