### ISSUE TITLE
Failable actions

### ISSUE THREAD

**Issue by philipengberg** [RxSwiftCommunity/Action#20]
How do you make an action failable?

I would like to do something like this:

``` swift
class SomeClass {

    var cancelAction: CocoaAction

    init() {
        cancelAction = CocoaAction {
            if someBooleanExpression {
                return failWith(CancelError.UnsavedChanges)
            }
            return just()
        }
    }
}
```

but the compiler throws up and says:

```
Variable 'self.cancelAction' used before being initialized
```

Which apparently has something to do with the `if` statement in an initializer.

I can't find any examples on doing this, so how would you go around and implement this correctly?

**Comment by ashfurrow** [comment]
Hey, great question! This is _really_ tricky, since the issue isn't with the fallibility as much as it is with Swift's initializer requirements. The problem is that you're (probably?) referring to `someBooleanExpression` as a reference to `self` from within the closure, which is against Swift's rules. 

An easy way around this is to make `cancelAction` an implicitly unwrapped optional:

```swift
var cancelAction: CocoaAction!
```

And it should be fine. 

Let me know if that works, if I can clarify anything, or if I misunderstood the question. Good luck!

**Comment by zipme** [comment]
@philipengberg I think you can also use a lazy variable:

```swift
 class SomeClass {

    lazy var cancelAction: CocoaAction = CocoaAction {
      if self.someBooleanExpression {
          return failWith(CancelError.UnsavedChanges)
       }
       return just()
   }()

   ...
}
```
