### ISSUE TITLE
Release to Cocoapods

### ISSUE THREAD

**Issue by philipengberg** [RxSwiftCommunity/Action#29]
I see that [this pull request](https://github.com/RxSwiftCommunity/Action/pull/23) should fix the RxSwift dependency issue, but it seems like this has not been released to cocoapods. 

If you [check the `.podspec`](https://github.com/CocoaPods/Specs/blob/master/Specs/Action/1.2.0/Action.podspec.json) on their end, it still contains the old dependencies.

**Comment by ashfurrow** [comment]
Good catch! Running into some problems validating the podspec (I've pushed 1.2.1 up here locally, but it won't validate on CocoaPods). Looking into it now...

**Comment by ashfurrow** [comment]
OK, so I've updated my version of Xcode, which has fixed _some_ errors. But then I saw this:

```
 -> Action (1.2.1)
    - ERROR | xcodebuild: Returned an unsuccessful exit code. You can use `--verbose` for more information.
    - ERROR | xcodebuild:  Action/Action.swift:38:57: error: type 'MainScheduler' has no member 'sharedInstance'
    - ERROR | xcodebuild:  Action/Action.swift:46:50: error: type 'MainScheduler' has no member 'sharedInstance'
    - ERROR | xcodebuild:  Action/Action.swift:59:9: error: use of unresolved identifier 'combineLatest'
    - ERROR | xcodebuild:  Action/Action.swift:70:30: error: use of unresolved identifier 'just'

[!] The podspec does not validate.
```

Which is weird since those _were_ being used but we changed them when RxSwift did. Then I looked at [the release](https://github.com/RxSwiftCommunity/Action/releases/tag/1.2.1) and there've been a bunch of commits since tagging it. I think I accidentally tagged this when my git was pointed to ashfurrow/Action instead of RxSwiftCommunity/Action. My fault. Will fix shortly.

**Comment by ashfurrow** [comment]
OK, should be up here: https://raw.githubusercontent.com/CocoaPods/Specs/04d650a2e7d40928aed028dd89444aa97303d636/Specs/Action/1.2.1/Action.podspec.json

This should fix #28 too. I'll wait to hear from you if that worked before closing either issue.

**Comment by philipengberg** [comment]
Works like a charm :dancer:

**Comment by ashfurrow** [comment]
Awesome! I'm going to close #28 then.
